name: Azure Static Web Apps CI/CD

on:
  push: { branches: [ main ] }
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'   # fija Node para evitar EBADENGINE
          cache: 'npm'

      - name: Install & Build (force linux lock + optional deps)
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          rm -rf node_modules package-lock.json
          npm i --no-audit --no-fund
          npm run build

      - name: List dist (debug)
        run: ls -la dist

      - name: Deploy (upload only dist)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BEACH_0CA82310F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "dist"
          skip_app_build: true
          config_file_location: "/"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BEACH_0CA82310F }}
          action: close
