name: Azure Static Web Apps CI/CD

on:
  push: { branches: [ main ] }
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.3

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: List dist (debug)
        run: ls -la dist

      - name: Deploy (upload only dist)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BEACH_0CA82310F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "dist"          # ⬅️ sube SOLO la carpeta dist
          skip_app_build: true          # ⬅️ NO dejes que Oryx reconstruya
          config_file_location: "/"     # ⬅️ tu staticwebapp.config.json está en la raíz
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BEACH_0CA82310F }}
          action: close
